config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'general#index', as: 'index'

  scope 'users', as: 'users' do
    get '/sign_up', to: 'user#signup', as: 'signup'
    post '/sign_up', to: 'user#signup_form', as: 'signupform'
    post '/login', to: 'user#login', as: 'login'
    get '/dashboard', to: 'user#dashboard', as: 'dashboard'
    get '/new_publication', to: 'user#new_publication', as: 'newpub'
    post '/new_publication', to: 'user#new_publication_form', as: 'newpubform'
    get '/new_publication/confirmation', to: 'user#new_publication_confirmation', as: 'newpubconfirmation'
    post '/new_publication/confirmation', to: 'user#new_publication_confirmation_form', as: 'newpubconfirmform'
    get '/publication/:id', to: 'user#destroy_pub', as: 'destroypub'
    get '/logout', to: 'user#destroy', as: 'destroy'
    get '/publication/modify/:id', to: 'user#edit', as: 'edit'
    post '/publication/modify/:id', to: 'user#editform', as: 'editform'
    get '/publication/comment/:id', to: 'user#comment', as: 'comment'
    post '/publication/comment/:id', to: 'user#comment_form', as: 'commentform'
    get '/profil', to: 'user#profil', as: 'profil'

  end

  get  '*path', controller: 'application', action: 'render_404'
  post '*path', controller: 'application', action: 'render_404'
  get  '*path', controller: 'application', action: 'render_500'
  post '*path', controller: 'application', action: 'render_500'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
	belongs_to :user
	belongs_to :publication
	validates :content, length: { in: 1..255 }
end

app/models/publication.rb
class Publication < ApplicationRecord
	belongs_to :user
	has_many :commentaires, :dependent => :delete_all
	mount_uploader :image, ImageUploader
	validates :content, length: { in: 0..255 }
end

app/models/user.rb
class User < ApplicationRecord

	has_many :publications
  	has_many :commentaires
	validates :nom, presence: true, length: { maximum: 30 }
	validates :prenom, presence: true, length: { maximum: 30 }
  	validates :email, presence: true, length: { maximum: 255 },
  						format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  	before_validation { email.downcase! }
  	#has_secure_password
  	validates :password, length: { minimum: 6 }
  	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500
  
  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end
  
  def render_500
    render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController

    def index
        render "general/index", layout: false
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def signup
		render "general/signup", layout: false
	end
	## Inscription
	def signup_form
		@user = User.new(user_params)
		if @user.save
			flash[:register_success] = "Vous vous êtes inscrit avec succès. Veuillez donc vous connecter. Merci"
			redirect_to '/'
		else
			flash[:register_errors] = @user.errors.full_messages
			redirect_to '/users/sign_up'
		end
	end
	## Connection
	def login
		@user = User.find_by(email:login_params[:email])
		if @user && @user.authenticate(login_params[:password])
			flash[:login_success] = "Connection réussie"
			session[:current_user_id] = @user.id
      		redirect_to '/users/dashboard'
	    else
	        flash[:login_errors] = "Identifiants incorrects"
	        redirect_to '/'
	    end
	end
	## dashboard
	def dashboard
		@publications = Publication.all
		@users = User.all
		@commentaires = Commentaire.all
		render "user/dashboard", layout: "layout"
	end
	## nouvelle publication
	def new_publication
		@publication = Publication.new
		render "user/new_pub", layout: "layout"
	end
	def new_publication_form
		#@content = pub_params[:content]
		#@image = pub_params[:image]
		#session[:pub_image] = pub_params[:image]
		#session[:pub_content] = pub_params[:content]
		@publication = Publication.new(pub_params) 
		render "user/new_pub_confirm", layout: "layout"
	end
	def destroy_pub
		@publication = Publication.find(params[:id])
	    @publication.destroy
	    flash[:pub_destroy] = "Post supprimé avec succès"
	    redirect_to '/users/dashboard'
	end
	def destroy
	    session[:current_user_id] = nil
	    flash[:notice_logout] = "Déconnection réussie"
	    redirect_to '/'
	end
	def edit
		@publication = Publication.find(params[:id])
		render "user/edit", layout: "layout"
	end
	def editform
		@publication = Publication.find(params[:id])
		if @publication.update(pub_params)
			flash[:pub_update] = "Post mis à jour avec succès"
			redirect_to '/users/dashboard'
		else
			flash[:pub_update_errors] = @publication.errors.full_messages
  			redirect_to users_edit_path(@publication)
  		end
	end
	def comment
		@commentaire = Commentaire.new
		session[:current_publication_id] = params[:id]
		render "user/comment", layout: "layout"
	end
	def comment_form
		@commentaire = Commentaire.new(comment_params)
		@commentaire.user_id = session[:current_user_id]
		@commentaire.publication_id = session[:current_publication_id]
		if @commentaire.save
			flash[:comment_success] = "Commentaire publiée avec succès"
			redirect_to '/users/dashboard'
		else
			flash[:comment_errors] = @commentaire.errors.full_messages
  			redirect_to users_comment_path(session[:current_publication_id])
		end
	end
	def profil
		@user = User.find(session[:current_user_id])
		render "user/profil", layout: "layout"
	end
	def new_publication_confirmation
		#@image = session[:pub_image]
		#@content = session[:pub_content]
		@publication = Publication.new(pub_params)
		render "user/new_pub_confirm", layout: "layout"
	end
	def new_publication_confirmation_form
		@publication = Publication.new(pub_params)
		@publication.user_id = session[:current_user_id]
		@publication.published_at = Time.now
		if @publication.save
			flash[:pub_success] = "Post publié avec succès"
			redirect_to '/users/dashboard'
		else
			flash[:pub_errors] = @publication.errors.full_messages
			redirect_to '/users/new_publication'
		end
	end
	## fonction privée
	private

		def user_params
			params.require(:user).permit(:nom, :prenom, :email, :gender, :date_of_birth, :password)
		end

		def login_params
	        params.require(:login).permit(:email, :password )
	    end

	    def pub_params
	        params.require(:publication).permit(:content, :image )
	    end
	    def comment_params
	        params.require(:commentaire).permit(:content)
	    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/general/index.html.erb
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<title>Connection ou Inscription - Facebook</title>
		
		<%= render "layouts/components/css" %>
	</head>

	<body>
		

		<div class="container" >

	      <div class="row " style="margin-top: 150px;">

	        <div class="col-md-1"></div>

	        <div class="col-md-6" style="margin-top: 40px; m">

	          <img class="img-fluid" style="width: 60%; margin-bottom: -15px; margin-left: -35px;" src="https://static.xx.fbcdn.net/rsrc.php/y8/r/dF5SId3UHWd.svg" alt="Facebook">
	          
	          <h2 style="font-weight: normal;"> Avec Facebook, partagez et restez en contact avec votre entourage.</h2>

	        </div>

	        <div class="col-md-4">

	          <div class="card">
	            <div class="card-body ">

	              <div class="errors">
	                    <% if flash[:register_success] %>	                      
	                        <p class="alert alert-success"> <%= flash[:register_success] %></p>	              
	                    <%end%>
	                    <% if flash[:login_errors] %>	                      
	                        <p class="alert alert-danger"> <%= flash[:login_errors] %></p>	              
	                    <%end%>
	                    <% if flash[:notice_logout] %>	                      
	                        <p class="alert alert-success"> <%= flash[:notice_logout] %></p>	              
	                    <%end%>
	              </div>

	              <form method="post" action="<%= users_login_path %>">

	                
	                <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

	                <div class="form-outline mb-4">
	                  <input type="email" id="email" class="form-control" name="login[email]" />
	                  <label class="form-label" for="email">Adresse e-mail ou numéro de tel.</label>
	                </div>

	                <!-- Password input -->
	                <div class="form-outline mb-4">
	                  <input type="password" id="password" class="form-control" name="login[password]"/>
	                  <label class="form-label" for="password">Mot de passe</label>
	                </div>

	                <!-- 2 column grid layout for inline styling -->
	                

	                <!-- Submit button -->
	                <button type="submit" class="btn btn-primary btn-block">Se connecter</button>
	                <br>
	                <div class="row  text-center">
	                  

	                  <div class="col">
	                    <!-- Simple link -->
	                    <a href="#!"> Mot de passe oublié ?</a>
	                  </div>
	                </div>
	              </form>
	              <hr>

	              <div class="text-center mt-4">
	              	<%= link_to 'Créer nouveau compte', users_signup_path, class: "btn btn-success" %>
	              </div>

	            </div>


	          </div>
	          <br>

	          <p class="text-center">Créer une Page pour une célébrité, un groupe ou une entreprise.</p>

	        </div>

	        <div class="col-md-1"></div>

	      </div>
	      
	    </div>

		
		<%= render "layouts/components/js" %>
	</body>

</html>

app/views/general/signup.html.erb
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<title>Connection ou Inscription - Facebook</title>
		
		<%= render "layouts/components/css" %>
	</head>

	<body>
		

		<div class="container" >

	      <div class="row " style="margin-top: 150px;">

	        <div class="col-md-1"></div>

	        <div class="col-md-6" style="margin-top: 40px; m">

	          <img class="img-fluid" style="width: 60%; margin-bottom: -15px; margin-left: -35px;" src="https://static.xx.fbcdn.net/rsrc.php/y8/r/dF5SId3UHWd.svg" alt="Facebook">
	          
	          <h2 style="font-weight: normal;"> Avec Facebook, partagez et restez en contact avec votre entourage.</h2>

	        </div>

	        <div class="col-md-4">

	          <div class="card">
	          	<div class="card-header text-center"><h1>Inscription</h1></div>
	            <div class="card-body ">

	              <div class="errors">
	                    <% if flash[:register_errors]%>
	                      <% flash[:register_errors].each do |error| %>
	                        <p class="alert alert-danger"> <%=error%></p>
	                      <%end%>
	                    <%end%>
	              </div>
	              <form method="post" action="<%= users_signupform_path %>">
	                <!-- Email input -->
	                <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

	                <div class="row ">

		                <div class="form-outline mb-4 col mr-4 ml-2">
		                  <input type="text" id="nom" class="form-control" name="user[nom]" />
		                  <label class="form-label" for="nom">Votre nom</label>
		                </div>

		                <div class="form-outline mb-4 col mr-2">
		                  <input type="text" id="prenom" class="form-control" name="user[prenom]" />
		                  <label class="form-label" for="prenom">Votre prénom</label>
		                </div>
		            </div>

	                <div class="form-outline mb-4">
	                  <input type="email" id="email" class="form-control" name="user[email]" />
	                  <label class="form-label" for="email">Votre adresse Email</label>
	                </div>

	                

		                <div class="form-outline datepicker mb-4">
						  <input
						    type="date"
						    class="form-control"
						    id="date_of_birth"
						    name="user[date_of_birth]"
						  />
						  <label for="date_of_birth" class="form-label">Sélectionner une date</label>
						</div>


						<div class="mb-4">
							<h1>Votre sexe</h1>
							<div class="form-check form-check-inline ml-28">
							  <input
							    class="form-check-input"
							    type="radio"
							    name="user[gender]"
							    id="mas"
							    value="M"
							  />
							  <label class="form-check-label" for="mas">Masculin</label>
							</div>

							<div class="form-check form-check-inline">
							  <input
							    class="form-check-input"
							    type="radio"
							    name="user[gender]"
							    id="fem"
							    value="F"
							  />
							  <label class="form-check-label" for="fem">Féminin</label>
							</div>
						</div>
					
	                
	                <div class="row ">

		                <div class="form-outline mb-4 col mr-4 ml-2">
		                  <input type="password" id="password" class="form-control" name="user[password]" />
		                  <label class="form-label" for="password">Votre mot de passe</label>
		                </div>

		                <div class="form-outline mb-4 col mr-2">
		                  <input type="password" id="password_confirmation" class="form-control" name="user[password_confirmation]" />
		                  <label class="form-label" for="password_confirmation">Confirmez votre mot de passe</label>
		                </div>
		            </div>
	                

	                <!-- 2 column grid layout for inline styling -->
	                

	                <!-- Submit button -->
	                <button type="submit" class="btn btn-primary btn-block">S'insrire</button>
	                <br>
	               
	              </form>
	              <hr>

	              <div class="text-center mt-4">
	              	Déjà inscrit?  &nbsp; 
	              	<%= link_to 'Cliquez ici', index_path, style: "color: blue;"%>
	              </div>

	            </div>


	          </div>
	          <br>

	          <p class="text-center">Créer une Page pour une célébrité, un groupe ou une entreprise.</p>

	        </div>

	        <div class="col-md-1"></div>

	      </div>
	      
	    </div>

		
		<%= render "layouts/components/js" %>
	</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/components/_footer.html.erb
<footer class="text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: #1a2649;">
    © All right reserved:
    <a class="text-white" href="<%= index_path %>">Facebook</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/components/_header.html.erb
<header>
	<header>
<style>
    #nav_menu{
      color: #1a2649;
      font-family: Arial;
      font-weight: bolder;
    }
    
    #btp:hover{
      color: white;
      background-color: #1a2649;
    }

    .current{

      border-bottom: #229ddc solid;
    }

    .dropbtn {
  
	  font-size: 16px;
	  border: none;
	}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: #1a2649;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: #ddd;}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {display: block;}

/* Change the background color of the dropdown button when the dropdown content is shown */
.dropdown:hover .dropbtn {}
    
  </style>

	


	<nav class="navbar navbar-expand-lg   navbar-light bg-light " style="margin-top: 15px;">
      <div class="container-fluid">
        <!-- Navbar brand -->
        <a class="navbar-brand nav-link"  href="<%= index_path %>" style="margin-left: 10px;">
          Facebook
        </a>
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation" style="background-color: #1a2649; color: white;">
          <i class="fas fa-bars" style="color: white;"></i>
        </button>  
        <div class="collapse navbar-collapse" id="navbarExample01">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0" style="margin-right: 50px;">
            
            
            

            <li class="nav-item" style="margin-right: 15px;">
              <a class="nav-link" href="<%= users_dashboard_path %>" id="nav_menu"  
                >Accueil</a>
            </li>

            
            <li class="nav-item" style="margin-right: 15px;">
              <a class="nav-link " href="<%= users_profil_path %>"  id="nav_menu">Profil</a>
            </li>
            &nbsp;
            
            

            <li class="nav-item" >
              <a
                  class="btn btn-info btn-rounded "
                  href="<%= users_newpub_path %>"
                  role="button"
                  style="  color: white;
                   background-color: #1a2649;
                   border-color: #1a2649; "
                  
               >Publier</a>
            </li>&nbsp;&nbsp;

            <li class="nav-item" >
              <a
                  class="btn btn-outline-info btn-rounded"
                  href="<%= users_destroy_path %>"
                  role="button"
                  style="  color: #1a2649;
                   background-color: white;
                   font-family: Arial;
      				font-weight: bolder; 
      				border-color: #1a2649;"
                  id="btp"
               >Se déconnecter</a>
            </li>
          </ul>

          
        </div>
      </div>
    </nav>


    
</header>
</header>

app/views/layouts/layout.html.erb
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<title> <%= yield :head %> - Facebook</title>
		
		<%= render "layouts/components/css" %>
	</head>

	<body>
		<%= render "layouts/components/header" %>

		<%= yield :content %>

		<%= render "layouts/components/footer" %>
		<%= render "layouts/components/js" %>
	</body>

</html>

app/views/user/comment.html.erb
<% content_for :head do %>
  Commenter - Publication
<% end %>

<% content_for :content do %>
  <div class="container-fluid mb-12">
    <div class="row mt-40">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            Commenter la publication.
          </div>
          <div class="card-body">
              <%= form_with(model: @commentaire, url: users_commentform_path, method: "post") do |form| %>

                <div class="form-outline mb-4">
                    <%= form.label :content, "Publication", class: "form-label" %>
                  <%= form.text_area :content, size: "70x5", class: "form-control" %>

                </div>
              <div class="text-center">
                <%= form.submit "Commenter", class: "btn btn-success  mb-4", style: "padding-right: 50px; padding-left: 50px; font-size: 17px;" %>
              </div>
            <% end %>
          </div>
          <div class="card-footer">
            Commenter - Publication - Facebook
          </div>
        </div>
      </div>
      <div class="col-md-4">
       
      </div>  
    </div>
    
  </div>
<% end %>

app/views/user/dashboard.html.erb
<% content_for :head do %>
  Tableau de bord
<% end %>

<% content_for :content do %>
  <div class="container-fluid">
    <div class="row">
      <% if flash[:pub_success] %>                       
          <p class="alert alert-success"> <%= flash[:pub_success] %></p>                
      <%end%>
      <% if flash[:pub_destroy] %>                       
          <p class="alert alert-warning"> <%= flash[:pub_destroy] %></p>                
      <%end%>
      <% if flash[:pub_update] %>                       
          <p class="alert alert-success"> <%= flash[:pub_update] %></p>                
      <%end%>
      <% if flash[:comment_success] %>                       
          <p class="alert alert-success"> <%= flash[:comment_success] %></p>                
      <%end%>
    </div>
    <% @publications.each do |publication| %> 
      <div class="row mb-12">
        <div class="col-md-9">
          <div class="card">
            <div class="card-header">
              <i class="fas fa-user"></i> &nbsp;
              <% @users.each do |user| %>
                <% if user.id == publication.user_id %>
                  <%= user.nom %> &nbsp; <%= user.prenom %> 
                <%end%>
              <%end%>
            </div>
            <div class="card-body">
              <%= publication.content %>
              <br>
              <% if publication.image.blank? %>
                <img src="https://mdbootstrap.com/img/new/slides/041.jpg" style="width: 100%; height: 500px;" class="img-fluid">             
              <% else %>
                <img src="<%= publication.image %>" style="width: 100%; height: 500px;" class="img-fluid">
              <%end%>
              
            </div>
            <div class="card-footer">
              <h1>Commentaires</h1>
              <% @commentaires.each do |commentaire| %>
                <% if publication.id == commentaire.publication_id %>

                  
                    <i class="fas fa-user"></i> &nbsp;
                    <% @users.each do |useri| %>
                        <% if useri.id == commentaire.user_id %>
                          <%= useri.nom %>
                        <% end %>
                    <% end %>

                    <br>

                        <%= commentaire.content %>

                  
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card">
            <div class="card-body pt-56 flex pl-0">
              
                <% if session[:current_user_id] == publication.user_id %>
                  <a href="<%= users_comment_path(publication) %>" class="btn btn-warning">Commenter</a>
                  &nbsp;&nbsp;
                  <a href="<%= users_edit_path(publication) %>" class="btn btn-info">Modifier</a>&nbsp;&nbsp;
                  <a href="<%= users_destroypub_path(publication) %>" class="btn btn-danger">Supprimer</a>
                <%else%> 
                  <a href="<%= users_comment_path(publication) %>" class="btn btn-warning">Commenter</a>
                <%end%>
              
                            
            </div>
          </div>
        </div>  
      </div>
    <%end%>
    
  </div>
<% end %>

app/views/user/edit.html.erb
<% content_for :head do %>
  Editer - Publication
<% end %>

<% content_for :content do %>
  <div class="container-fluid mb-12">
    <div class="row mt-40">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            Editer votre publication.
          </div>
          <div class="card-body">
              <%= form_with(model: @publication, url: users_editform_path, method: "post") do |form| %>

                <div class="form-outline mb-4">
                <%= form.label :image, "Ajouter une photo(optionnel)", class: "form-label" %>
                <%= image_tag(@publication.image.url) if @publication.image && @publication.image.url %>
                  <%= form.file_field :image, class: "form-control" %>

                </div>

                <div class="form-outline mb-4">
                    <%= form.label :content, "Publication", class: "form-label" %>
                  <%= form.text_area :content, size: "70x5", class: "form-control" %>

                </div>


              <div class="text-center">
                <%= form.submit "Publier", class: "btn btn-success  mb-4", style: "padding-right: 50px; padding-left: 50px; font-size: 17px;" %>
              </div>
            <% end %>
          </div>
          <div class="card-footer">
            Editer - Publication - Facebook
          </div>
        </div>
      </div>
      <div class="col-md-4">
       
      </div>  
    </div>
    
  </div>
<% end %>

app/views/user/new_pub.html.erb
<% content_for :head do %>
  Nouvelle publication
<% end %>

<% content_for :content do %>
  <div class="container-fluid mb-12">
    <div class="row mt-40">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            Nouvelle Publication
          </div>
          <div class="card-body">

            <div class="row">
              <% if flash[:pub_errors]%>
                <% flash[:pub_errors].each do |error| %>
                  <p class="alert alert-danger"> <%=error%></p>
                <%end%>
              <%end%>
            </div>

            <%= form_with(model: @publication, url: users_newpubform_path, method: "post") do |form| %>

                <div class="form-outline mb-4">
                <%= form.label :image, "Ajouter une photo(optionnel)", class: "form-label" %>
                <%= image_tag(@publication.image.url) if @publication.image && @publication.image.url %>
                  <%= form.file_field :image, class: "form-control" %>

                </div>

                <div class="form-outline mb-4">
                    <%= form.label :content, "Publication", class: "form-label" %>
                  <%= form.text_area :content, size: "70x5", class: "form-control" %>

                </div>


              <div class="text-center">
                <%= form.submit "Publier",data: { confirm: 'Your message Here' }, class: "btn btn-success  mb-4", style: "padding-right: 50px; padding-left: 50px; font-size: 17px;" %>
              </div>
            <% end %>
            

          </div>
          <div class="card-footer">
             Créer une nouvelle publication - Facebook
          </div>
        </div>
      </div>
      <div class="col-md-4">
        
      </div>  
    </div>
    
  </div>
<% end %>

app/views/user/new_pub_confirm.html.erb
<% content_for :head do %>
  Confirmation - Nouvelle Publication
<% end %>

<% content_for :content do %>
  <div class="container-fluid mb-12">
    <div class="row mt-40">
      <div class="col-md-9">
        <div class="card">
          <div class="card-header">
            Veuillez Confirmer votre nouvelle publication.
          </div>
          <div class="card-body">
              <img src="<%= @publication.image %>">

              <p><%= @publication.content %></p>
          </div>
          <div class="card-footer">
            Confirmation - Nouvelle Publication - Facebook
          </div>
        </div>
      </div>
      <div class="col-md-3">
          <%= form_with(model: @publication, local: true, url: users_newpubconfirmform_path) do |form| %>

            <%= form.hidden_field :image %>
            <%= form.hidden_field :content %>
            <%= form.submit "Confirmer", class: "btn btn-primary" %>
          <% end %>
          
      </div>  
    </div>
    
  </div>
<% end %>

app/views/user/profil.html.erb
<% content_for :head do %>
  Profil
<% end %>

<% content_for :content do %>
  <div class="container-fluid mb-12">
    <div class="row mt-40">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            Vos Informations
          </div>
          <div class="card-body">
              <p>Noms & prénoms: <%= @user.nom %> &nbsp; <%= @user.prenom %></p>
              <p>Email: <%= @user.email %></p>
              <p>Sexe: 
                <%if @user.gender == "M" %>
                  Masculin
                <% else %>
                  Féminin
                <% end %>
              </p>
              <p>Date d'anniversaire: <%= @user.date_of_birth %></p>
          </div>
          <div class="card-footer">
            Profil - Informations - Facebook
          </div>
        </div>
      </div>
      <div class="col-md-4">
       
      </div>  
    </div>
    
  </div>
<% end %>